### ISSUE TITLE
Unable to access file within /var/log

### ISSUE THREAD

**Issue by trevor-criblio** [paulsena/Cribl-Log-Collector-Interview#5]
From the acceptance criteria (point 4.a), there should be the ability to specify a filename with `/var/log` when selecting the log file to read. However, I'm currently unable to do this:
![image](https://github.com/paulsena/Cribl-Log-Collector-Interview/assets/94069108/03978cd7-9e1b-4f6f-89c4-3abb7b9a6d97)

**Comment by paulsena** [comment]
Hey @trevor-criblio , thanks for reviewing my submission!

That is by design. I read the requirements as the ability to specify just a filename within a preset log directory. It is an extremely vulnerable attack vector to be able to allow the client to specify any root directory or even relative path directory (can escape out using ../../ ) as this allows them to browse the server's filesystem via the WS.

At the application level, the directory can be configured to any path using the property file: 
`/resources/application.properties`

I explained my some of my reasoning and design in the READM.md file. Hope that helps!

**Comment by trevor-criblio** [comment]
Thanks - passed over that the first time around :man_facepalming:. Sorry about that!

Suppose I want to be able to access files within nested directories (say `/var/log/foo.log` as well as `/var/log/apt/foo.log`) - is there a way for me to currently do this, or will I be limited to only one level within one specified directory? (don't necessarily need a solution implemented here, just wondering what your approach might be to keep me within my specified dir while still having more freedom about which logs I want to query)

**Comment by paulsena** [comment]
No problem Trevor,

Yea, my current implementation I don't allow any paths specified in the WS request b/c of the potential vulnerability of just one backslashing "../" being able to escape out of intended directory. 

Currently, you would need to change the config file and restart. A more flexible longer term solution would be to allow that config to be a whitelist of allowed directories to scan.
